### ISSUE TITLE
Python error at first launch: unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by SteamWind** [fdw/rofimoji#55]
Hello, I compiled an installed rofimoji with the `setup.py`.
When I launch `rofimoji` in my shell, here is the output:
```python
Traceback (most recent call last):
  File "/usr/local/bin/rofimoji", line 11, in <module>
    load_entry_point('rofimoji==4.3.0', 'console_scripts', 'rofimoji')()
  File "/usr/local/lib/python3.6/dist-packages/rofimoji-4.3.0-py3.6.egg/picker/Rofimoji.py", line 360, in main
    Rofimoji()
  File "/usr/local/lib/python3.6/dist-packages/rofimoji-4.3.0-py3.6.egg/picker/Rofimoji.py", line 47, in __init__
    self.active_window = self.typer.get_active_window()
  File "/usr/local/lib/python3.6/dist-packages/rofimoji-4.3.0-py3.6.egg/picker/Typer.py", line 47, in get_active_window
    encoding='utf-8').stdout[:-1]
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
I tried to launch it without arguments and with those arguments too but the issue is the same:
```rofimoji --clipboarder xclip --typer xdotool```

Do you know what could I do to make it work?
Thanks!

**Comment by fdw** [comment]
I think the problem is that `capture_output` was introduced with Python 3.7. Do you have a later Python version?

**Comment by SteamWind** [comment]
Oh yes, I was using Python 3.6, trying to update

**Comment by SteamWind** [comment]
Thank you, worked with 3.9
Maybe it could be referenced here:
https://github.com/fdw/rofimoji#dependencies

(now trying to make if work with i3vm :smile: )

**Comment by fdw** [comment]
Will do; I hadn't known that that was so recent 🙈
